login/urls.py
from django.conf.urls import url
from .views import *

# /sol
from .custom_auth import auth_login, auth_logout

urlpatterns = [
	url(r'^$', index, name='index'),

    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout')
    ]

profile_me/urls.py
from django.conf.urls import url, include
from .views import index, update, add_status, delete_status
 
urlpatterns = [

    url(r'^$', index, name = "index"),
    url(r'^update/', update, name = "update"),
	url(r'^add_status', add_status, name='add_status'),
	url(r'^delete_status/(?P<id_status>\d+)/$', delete_status, name = 'delete_status'),
]

temenin/urls.py
from django.shortcuts import redirect
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import login.urls as login
import profile_me.urls as profile

urlpatterns = [
    url(r'', include(login , namespace='login')),
    url(r'^$',  RedirectView.as_view(url='login/',permanent=True), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(profile,namespace='profile_me')),
    url(r'^status/', include(profile , namespace='status')),

]

profile_me/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    nama = models.CharField(max_length = 100)
    npm = models.CharField(max_length = 100)
    keahlian = models.TextField()
    tingkat_keahlian = models.TextField()
    emailku = models.EmailField()
    tampilkan_nilai = models.BooleanField()
    profile_linkedin = models.URLField()

    def to_dict(self):
        result = {}
        result['nama'] = self.nama
        result['npm'] = self.npm
        result['email'] = self.emailku
        result['tampilkan_nilai'] = self.tampilkan_nilai
        result['profile_link'] = self.profile_linkedin

        # pisahkan semua keahlian menjadi list
        keahlianku = []
        hasil = ''
        for i in self.keahlian:
            if i == '+':
                keahlianku.append(hasil)
                hasil = ''
            else :
                hasil+=i
        keahlianku.append(hasil)

        # pisahkan semua tingkatkeahlian menjadi list juga
        tingkat = []
        hasil = ''
        for i in self.tingkat_keahlian:
            if i == "+":
                tingkat.append(hasil)
                hasil = ''
            else :
                hasil += i
        tingkat.append(hasil)
        ahlitingkat = []
        counter = 0
        for i in range(len(keahlianku)):
            ahlitingkat.append([])
            ahlitingkat[counter].append(keahlianku[i])
            ahlitingkat[counter].append(tingkat[i])
            counter+=1
        result['keahlian'] = ahlitingkat
        return result

profile_me/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib import messages
from .models import User
import requests
from django.shortcuts import render
from update_status.models import StatusKu
from update_status.forms import Form_status
from django.http import HttpResponseRedirect

# Create your views here.

RIWAYAT_API = 'https://private-e52a5-ppw2017.apiary-mock.com/riwayat'
response = {}

def index(request):
    if request.session['user_login'] is None:
        response['login'] = False
        response['logintrue'] = False
        return HttpResponseRedirect(reverse('login:auth_login'))
    else : 
        html = 'profile.html'
        boo = request.session['kode_identitas']
        user = User.objects.filter(npm = boo)
        response = {}
        if len(user) > 1:
            response = user[0].to_dict()
        else:
            usernew = create_user(request)
            response = usernew.to_dict()
        response['riwayats'] = get_riwayat()
        # TODO ngambil rahasia dari objek mahasiswa
        set_data_for_session(request)
        kode_identitas = get_data_user(request, 'kode_identitas')
        response['test'] = 'hai halo'
        response['login'] = True
        statusnya = StatusKu.objects.order_by('-id')
        response['status_form'] = Form_status
        response['status'] = statusnya
        response['logintrue'] = True
        return render(request, html, response)

# -------------- creating user if not exist in database ----------------------- #
def create_user(requests) :
    print('->create_user')
    creature = User(nama=requests.session['user_login'], npm=requests.session['kode_identitas'], keahlian = "", tingkat_keahlian="", emailku="", tampilkan_nilai = True, profile_linkedin = "")
    creature.save()
    return creature
# -------------- creating user if not exist in database ----------------------- #

def add_status(request):
    form = Form_status(request.POST or None)
    set_data_for_session(request)
    kode_identitas = get_data_user(request, 'kode_identitas')
    pengguna = User.objects.get(npm = kode_identitas)
    if(request.method == 'POST' and form.is_valid()):
        print('dia adalah=>',pengguna)
        response['description'] = request.POST['description']
        status = StatusKu(pengguna = pengguna, description=response['description'])
        #status.pengguna = pengguna
        status.save()
        return HttpResponseRedirect('/status/')
    else:
        return HttpResponseRedirect('/status/')

def delete_status(request, id_status):
    status = StatusKu.objects.get(pk = id_status)
    status.delete()
    return HttpResponseRedirect('/status/')

def get_data_user(request, tipe):
    data = None
    if tipe == "user_login" and 'user_login' in request.session:
        data = request.session['user_login']
    elif tipe == "kode_identitas" and 'kode_identitas' in request.session:
        data = request.session['kode_identitas']
    elif tipe == "role" and 'role' in request.session:
        data = request.session['role']
    return data

def set_data_for_session(request):
    response['author'] = get_data_user(request, 'user_login')
    response['kode_identitas'] = request.session['kode_identitas']
    response['role'] = request.session['role']

def get_riwayat():
	riwayat = requests.get(RIWAYAT_API)
	return riwayat.json()

# ------------------ Update profile ------------------------ #
def update(request):
    html = "update.html"
    return render(request, html, response)

def updatedata(request):
    if request.method == 'POST':
        hehe =1

    return HttpResponseRedirect(reverse('profile_me:index'))

profile_me/templates/footer.html
<p> Made by love with us </p>

profile_me/templates/profile.html
{% extends "profile/base.html" %}

{% block content %}
<div class="container" style="padding-top: 0px">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="card">
        <img class="cover" src="https://wallpapercave.com/wp/PSksftM.jpg" alt="cover" />
        <img class="picture img-circle" src="http://orig12.deviantart.net/e40f/f/2012/239/a/d/aang_facebook_default_profile_picture_by_redjanuary-d5cm82l.png" alt="profpic" />
        <h1>Selamat datang, {{ nama }}</h1>
        <h3>lihat forum</h3>
        <h3>Jumlah Status</h3>
        <h3>Tidak ada status terbaru</h3>
      </div>
    </div>
  </div>
</div>

<div class="container" style="padding-top: 30px; padding-bottom:40px">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <a class="postStatus btn btn-info btn-lg btn-block" style="float:left; " href ="{% url 'profile_me:update' %}">Change Profile</a>
      </div>
  </div>
</div>

<div>
    <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-justified" role="tablist">
        <li role="presentation" class="active">
            <a href="#profile" aria-controls="home" role="tab" data-toggle="tab"> Profile </a>
        </li>
        <li role="presentation">
            <a href="#riwayat" aria-controls="settings" role="tab" data-toggle="tab"> Riwayat </a>
        </li>
        <li role="presentation">
            <a href="#updatestat" aria-controls="settings" role="tab" data-toggle="tab"> Update Status </a>
        </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade in active" id="profile">
            {% include 'profile_iner.html' %}
        </div>
        <div role="tabpanel" class="tab-pane fade" id="riwayat">
            {% include 'riwayat/riwayat.html' %}
        </div>
        <div role="tabpanel" class="tab-pane fade" id="updatestat">
            {% include 'status/status.html' %}
        </div>
    </div>
</div>


{% endblock %}

profile_me/templates/profile_iner.html
<div class="panel-body">
    <table class="table">
        <tbody>
        <tr>
            <td> Nama </td>
            <td> {{ nama }}</td>
        </tr>
        <tr>
            <td> NPM </td>
            <td> {{ npm }}</td>
        </tr>
        <tr>
            <td> Email </td>
            {% if email %}
            <td> {{ email }}</td>
            {% else %}
            <td> Not Set </td>
            {% endif %}
        </tr>
        <tr>
            <td> Keahlian </td>
            <td>
                {% if keahlian %}
                    {% for keahliannya in keahlian %}
                    <div class = "{{keahliannya.1}}">{{ keahliannya.0 }}</div>
                    {% endfor %}
                {% else %}
                <div class = "none">Not Set</div>
                {% endif %}
            </td>
        </tr>
        <tr>
            <td> Profile LinkedIn </td>
            {% if profile_link %}
            <td> {{ profile_link }} </td>
            {% else %}
            <td> Not Linked </td>
            {% endif %}
        </tr>
        </tbody>
    </table>
</div>

profile_me/templates/update.html
{% extends "profile/base.html" %}
{% block content %}
<div class = "container">
    Link to your linkedin<br>
    <a href ="https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id=81gg7azbk3idvt&redirect_uri=https%3A%2F%2Fwww.example.com%2Fauth%2Flinkedin&state=987654321&scope=r_basicprofile,r_emailaddress" class ="">link to linkedin</a>
    <br>
    Tampilkan Nilai
    <form id = 'tampilkan'>
        <input type="radio" name="tampil" value="ya">Ya<br>
        <input type="radio" name="tampil" value="tidak">Tidak
    </form>
    Keahlian
    <div class = "container-select" id = "selecting">
        <select class="skill"></select>
        <select class="level"></select>
    </div>

    <button class="postStatus btn btn-info btn-lg btn-block" id = "tambah_keahlian">Tambah Keahlian</button>
    <button class="postStatus btn btn-info btn-lg btn-block" id = "save">Save</button>

</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="//platform.linkedin.com/in.js">
    api_key: 81gg7azbk3idvt
    onLoad: onLinkedInLoad()
    authorize: true
    lang:      
</script>

<script type="text/javascript">
    var email = '';
    var foto = '';
    // Setup an event listener to make an API call once auth is complete
    function onLinkedInLoad() {
        IN.Event.on(IN, "auth", getProfileData);
    }

    // Handle the successful return from the API call
    function onSuccess(data) {
        email = data.email-address;
        foto = data.public-profile-url;
    }

    // Handle an error response from the API call
    function onError(error) {
        console.log(error);
    }

    // Use the API call wrapper to request the member's basic profile data
    function getProfileData() {
        IN.API.Raw("/people/~:(first-name,last-name,headline,email-address,picture-url,public-profile-url)").result(onSuccess).error(onError);
    }

    $('#tambah_keahlian').on('click', function(){
        var satu = '<select class="skill"></select>';
        var dua = '<select class="level"></select>';
        $('#selecting').append(satu);
        $('#selecting').append(dua);
    })

    $('#save').on('click'), function(){
        var ahlian = document.getElementsByClassName("skill");
        var tingkat = document.getElementsByClassName("level");
        var yaTidak = $('input[name=tampil]:checked', '#myForm').val();
        $.ajax({
            method: "POST",
            url: "{% url 'profile_me:updatedata' %}",
            data: {'ahli':ahlian, 'tingkat':tingkat, 'yatidak':yaTidak, 'email':email, 'urlpic':foto },
            success: function (results)
            {

            }
        });
    }
</script>

{% endblock %}