login/urls.py
from django.conf.urls import url
from .views import *

# /sol
from .custom_auth import auth_login, auth_logout

urlpatterns = [
	url(r'^$', index, name='index'),

    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout')
    ]

temenin/urls.py
from django.shortcuts import redirect
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import login.urls as login
import profile_me.urls as profile

urlpatterns = [
    url(r'', include(login , namespace='login')),
    url(r'^$',  RedirectView.as_view(url='login/',permanent=True), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(profile,namespace='profile_me')),
    url(r'^status/', include(profile , namespace='status')),

]

login/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import json
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from profile_me.models import User



# Create your views here.
response = {}
def index(request):
    print ("#==> masuk index")
    if 'user_login' in request.session:

        return HttpResponseRedirect(reverse('profile_me:index'))
    else:
        response['login'] = False;
        html = 'login/login.html'
        return render(request, html, response)

login/templates/login/login.html
{% extends "login/layout/base.html" %}
{% block content %}
<div class="navbar navbar-default navbar-fixed-top" role="navigation" >
    <div class="container"> 
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span> 
            </button>
            <a href="#" class="navbar-brand">temenin</a>
        </div>
    </div>
</div>
<div class="row" style="margin-top: 50px">
    <div class="col-md-6 col-md-offset-3">
        <div class="rata-tengah">
            <div class="judul">
                <h1> Halaman Login </h1>
                <p class="text-info"> Gunakan <b> akun SSO </b> untuk login </p>
            </div>
            <form action="{% url 'login:auth_login' %}" method="POST">
                {% csrf_token %}
                <p>
                    <label for="username"> Your username </label>
                    <input type="text" id="username" name="username" required>
                </p>
                <p>
                    <label for="password"> Your password </label>
                    <input type="password" id="password" name="password" required>
                </p>
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>
{% endblock %}